


before_install:
    - sudo apt-get install -y autofs attr gdb uuid-dev uuid
    - wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-config/cvmfs-config-default_1.1-1_all.deb
    - sudo dpkg -i cvmfs-config-default_1.1-1_all.deb
    - wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.1.20/cvmfs_2.1.20_amd64.deb
    - sudo dpkg -i cvmfs_2.1.20_amd64.deb
install:
    - 'sudo sh -c "echo CVMFS_HTTP_PROXY=\"http://ca-proxy.cern.ch:3128;http://ca-proxy1.cern.ch:3128|http://ca-proxy2.cern.ch:3128|http://ca-proxy3.cern.ch:3128|http://ca-proxy4.cern.ch:3128|http://ca-proxy5.cern.ch:3128\" >> /etc/cvmfs/default.local"'
    - 'sudo sh -c "echo CVMFS_REPOSITORIES=lhcb >> /etc/cvmfs/default.local"'
    - 'service autofs start'
script:
    - sudo cvmfs_config chksetup
    - sudo cvmfs_config probe


