
language: c

before_install:
    # Set up user-mode FUSE
    - sudo apt-get install -qq libfuse-dev pkg-config fuse user-mode-linux
    - sudo mknod /dev/fuse c 10 229
    - sudo chmod 666 /dev/fuse
    # Install CVMFS
    - sudo apt-get install -y autofs attr gdb uuid-dev uuid fuse
    - wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-config/cvmfs-config-default_1.1-1_all.deb
    - sudo dpkg -i cvmfs-config-default_1.1-1_all.deb
    - wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.1.20/cvmfs_2.1.20_amd64.deb
    - sudo dpkg -i cvmfs_2.1.20_amd64.deb
install:
    - 'sudo sh -c "echo CVMFS_HTTP_PROXY=\"http://ca-proxy.cern.ch:3128;http://ca-proxy1.cern.ch:3128|http://ca-proxy2.cern.ch:3128|http://ca-proxy3.cern.ch:3128|http://ca-proxy4.cern.ch:3128|http://ca-proxy5.cern.ch:3128\" >> /etc/cvmfs/default.local"'
    - 'sudo sh -c "echo CVMFS_REPOSITORIES=lhcb.cern.ch >> /etc/cvmfs/default.local"'
    - 'sudo sh -c "echo user_allow_other >> /etc/fuse.conf"'
    - sudo useradd -a -G fuse cvmfs
    - sudo service autofs restart
script:
    - sudo cvmfs_config chksetup
    - sudo cvmfs_config probe


